version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-nikahsalon
    environment:
      POSTGRES_USER: enescikcik
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: nikahsalon
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enescikcik"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
